# Generated by Django 5.1 on 2025-12-01 18:37

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('idobra_social', models.AutoField(db_column='idObra_social', primary_key=True, serialize=False)),
                ('nombre', models.CharField(choices=[('PAMI', 'PAMI'), ('OSDE', 'OSDE'), ('IOMA', 'IOMA'), ('INSSSEP', 'INSSSEP'), ('Otra', 'Otra')], max_length=50, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'obra_social',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idpaciente', models.AutoField(db_column='idPaciente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.IntegerField(blank=True, null=True, unique=True)),
                ('pais', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('pasaporte', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('domicilio', models.CharField(blank=True, max_length=100, null=True)),
                ('localidad', models.CharField(blank=True, max_length=50, null=True)),
                ('provincia', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10)),
                ('nro_afiliado', models.IntegerField(blank=True, null=True)),
                ('diabetes', models.BooleanField()),
                ('hipertension', models.BooleanField()),
                ('fumador', models.BooleanField()),
                ('alergias', models.CharField(blank=True, max_length=256, null=True)),
                ('antecedentes', models.CharField(blank=True, max_length=256, null=True)),
                ('cirugias', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('estado', models.CharField(choices=[('Vivo', 'Vivo'), ('Difunto', 'Difunto')], default='Vivo', max_length=10)),
                ('obra_social', models.ForeignKey(blank=True, db_column='idObra_social', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacientes.obrasocial')),
            ],
            options={
                'db_table': 'paciente',
                'managed': True,
            },
        ),
    ]
