# Generated by Django 5.1 on 2025-02-28 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('idobra_social', models.AutoField(db_column='idObra_social', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cuit', models.IntegerField()),
                ('tipo', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'obra_social',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idpaciente', models.AutoField(db_column='idPaciente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.IntegerField(unique=True)),
                ('domicilio', models.CharField(blank=True, max_length=100, null=True)),
                ('localidad', models.CharField(blank=True, max_length=50, null=True)),
                ('provincia', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10)),
                ('nro_afiliado', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=256)),
                ('diabetes', models.BooleanField()),
                ('hipertension', models.BooleanField()),
                ('fumador', models.BooleanField()),
                ('alergias', models.CharField(blank=True, max_length=256, null=True)),
                ('antecedentes', models.CharField(blank=True, max_length=256, null=True)),
                ('cirugias', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('obra_social', models.ForeignKey(blank=True, db_column='idObra_social', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacientes.obrasocial')),
            ],
            options={
                'db_table': 'paciente',
                'managed': True,
            },
        ),
    ]
