# Generated by Django 5.1 on 2025-03-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='estado',
            field=models.CharField(choices=[('Vivo', 'Vivo'), ('Difunto', 'Difunto')], default='Vivo', max_length=10),
        ),
    ]
