# Generated by Django 5.1 on 2025-05-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obrasocial',
            name='nombre_titular',
        ),
        migrations.RemoveField(
            model_name='obrasocial',
            name='nro_afiliado',
        ),
        migrations.RemoveField(
            model_name='obrasocial',
            name='nro_beneficiario_titular',
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
