# Generated by Django 5.1 on 2025-03-05 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='descripcion',
        ),
    ]
