# Generated by Django 5.1 on 2025-05-08 21:23

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_alter_paciente_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='pais',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='pasaporte',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
