# Generated by Django 5.1 on 2025-05-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_paciente_pais_paciente_pasaporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='pasaporte',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
