# Generated by Django 5.1 on 2025-12-01 18:37

import django.db.models.deletion
import habitaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('idhabitacion', models.AutoField(db_column='idHabitacion', primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('cantidad_camas', models.IntegerField()),
                ('tipo', models.CharField(choices=[('VIP', 'VIP'), ('UCI', 'UCI'), ('FEM', 'Femenina'), ('MIX', 'Mixta'), ('PED', 'Pediátrica'), ('MAT', 'Maternidad'), ('PSI', 'Psiquiátrica')], max_length=3)),
            ],
            options={
                'db_table': 'habitacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('idsector', models.AutoField(db_column='idSector', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='tipo', max_length=100, verbose_name='Nombre del Sector')),
                ('cantidad_habitaciones', models.IntegerField()),
                ('piso', models.IntegerField()),
            ],
            options={
                'db_table': 'sector',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cama',
            fields=[
                ('idcama', models.AutoField(db_column='idCama', primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('L', 'Libre'), ('O', 'Ocupada'), ('R', 'Reservada')], default='L', max_length=1)),
                ('nro_cama', models.IntegerField(default=0)),
                ('habitacion', models.ForeignKey(db_column='idHabitacion', on_delete=django.db.models.deletion.CASCADE, related_name='camas', to='habitaciones.habitacion')),
            ],
            options={
                'db_table': 'cama',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField(default=habitaciones.models.default_expiracion)),
                ('cama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='habitaciones.cama')),
            ],
            options={
                'db_table': 'reserva',
                'managed': True,
            },
        ),
    ]
