# Generated by Django 5.1 on 2025-03-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='tipo',
            field=models.CharField(choices=[('GEN', 'General'), ('TER', 'Terapia'), ('VIP', 'VIP'), ('QUI', 'Quirófano'), ('NEO', 'Neonatología')], max_length=3),
        ),
    ]
