# Generated by Django 5.1 on 2025-05-21 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitaciones', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='personal.medico'),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='idsector',
            field=models.ForeignKey(db_column='idSector', on_delete=django.db.models.deletion.PROTECT, related_name='habitaciones', to='habitaciones.sector'),
        ),
    ]
