# Generated by Django 5.1 on 2025-03-05 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0002_alter_sector_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='idsector',
            field=models.ForeignKey(db_column='idSector', on_delete=django.db.models.deletion.PROTECT, related_name='habitaciones', to='habitaciones.sector'),
        ),
    ]
