# Generated by Django 5.1 on 2025-03-05 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0003_alter_habitacion_idsector'),
        ('pacientes', '0003_remove_paciente_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cama',
            name='paciente',
            field=models.ForeignKey(blank=True, db_column='idPaciente', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camas', to='pacientes.paciente'),
        ),
    ]
