# Generated by Django 5.1 on 2025-03-06 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0004_alter_cama_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cama',
            name='paciente',
        ),
    ]
