# Generated by Django 5.1 on 2025-03-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0006_alter_sector_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='tipo',
            field=models.CharField(choices=[('GENERAL', 'General'), ('TERAPIA', 'Terapia'), ('VIP', 'VIP'), ('QUIRÓFANO', 'Quirófano')], max_length=15),
        ),
    ]
