# Generated by Django 5.1 on 2025-03-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0007_alter_sector_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='tipo',
            field=models.CharField(choices=[('GEN', 'General'), ('TER', 'Terapia'), ('VIP', 'VIP'), ('QUI', 'Quirófano')], max_length=15),
        ),
    ]
