# Generated by Django 5.1 on 2025-04-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0008_alter_sector_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='tipo',
            field=models.CharField(choices=[('General', 'General'), ('Terapia', 'Terapia'), ('VIP', 'VIP'), ('Quirófano', 'Quirófano')], max_length=15),
        ),
    ]
