# Generated by Django 5.1 on 2025-04-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0009_alter_sector_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cama',
            name='nro_cama',
            field=models.IntegerField(default=0),
        ),
    ]
