# Generated by Django 5.1 on 2025-02-28 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitaciones', '0001_initial'),
        ('pacientes', '__first__'),
        ('personal', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internacion',
            fields=[
                ('idinternacion', models.AutoField(db_column='idInternacion', primary_key=True, serialize=False)),
                ('fecha_admision', models.DateTimeField()),
                ('fecha_alta', models.DateTimeField(blank=True, null=True)),
                ('nota_ingreso', models.CharField(max_length=256)),
                ('cama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitaciones.cama')),
                ('idpaciente', models.ForeignKey(db_column='idPaciente', on_delete=django.db.models.deletion.PROTECT, to='pacientes.paciente')),
            ],
            options={
                'db_table': 'internacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('iddiagnostico', models.AutoField(db_column='idDiagnostico', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, default=None, null=True)),
                ('detalles', models.CharField(blank=True, max_length=256, null=True)),
                ('gravedad', models.CharField(blank=True, max_length=256, null=True)),
                ('tratamiento', models.CharField(blank=True, max_length=256, null=True)),
                ('idmedico', models.ForeignKey(db_column='idMedico', on_delete=django.db.models.deletion.PROTECT, to='personal.medico')),
                ('idmedico_derivado', models.ForeignKey(blank=True, db_column='idMedico_derivado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnostico_como_derivado', to='personal.medico')),
                ('idpaciente', models.ForeignKey(db_column='idPaciente', on_delete=django.db.models.deletion.PROTECT, to='pacientes.paciente')),
                ('idinternacion', models.ForeignKey(blank=True, db_column='idInternacion', null=True, on_delete=django.db.models.deletion.CASCADE, to='internacion.internacion')),
            ],
            options={
                'db_table': 'diagnostico',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('idseguimiento', models.AutoField(db_column='idSeguimiento', primary_key=True, serialize=False)),
                ('observacion', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('idenfermero', models.ForeignKey(db_column='idEnfermero', on_delete=django.db.models.deletion.PROTECT, to='personal.enfermero')),
                ('idinternacion', models.ForeignKey(db_column='idInternacion', on_delete=django.db.models.deletion.CASCADE, to='internacion.internacion')),
            ],
            options={
                'db_table': 'seguimiento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Medicacion',
            fields=[
                ('idmedicacion', models.AutoField(db_column='idMedicacion', primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=45)),
                ('hora_medicacion', models.TimeField(max_length=45)),
                ('seguimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicaciones', to='internacion.seguimiento')),
            ],
            options={
                'db_table': 'medicacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('idsignos_vitales', models.AutoField(db_column='idSignos_vitales', primary_key=True, serialize=False)),
                ('temperatura_corporal', models.CharField(max_length=45)),
                ('pulso', models.CharField(max_length=45)),
                ('frecuencia_respiratoria', models.CharField(max_length=45)),
                ('seguimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signos_vitales', to='internacion.seguimiento')),
            ],
            options={
                'db_table': 'signos_vitales',
                'managed': True,
            },
        ),
    ]
