# Generated by Django 5.1 on 2025-12-01 18:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('iddiagnostico', models.AutoField(db_column='idDiagnostico', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('detalles', models.CharField(blank=True, max_length=256, null=True)),
                ('gravedad', models.CharField(blank=True, max_length=256, null=True)),
                ('tratamiento', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'diagnostico',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Internacion',
            fields=[
                ('idinternacion', models.AutoField(db_column='idInternacion', primary_key=True, serialize=False)),
                ('fecha_admision', models.DateTimeField()),
                ('fecha_alta', models.DateTimeField(blank=True, null=True)),
                ('nota_ingreso', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'internacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Medicacion',
            fields=[
                ('idmedicacion', models.AutoField(db_column='idMedicacion', primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=45)),
                ('hora_medicacion', models.TimeField(max_length=45)),
            ],
            options={
                'db_table': 'medicacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('idseguimiento', models.AutoField(db_column='idSeguimiento', primary_key=True, serialize=False)),
                ('observacion', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'seguimiento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('idsignos_vitales', models.AutoField(db_column='idSignos_vitales', primary_key=True, serialize=False)),
                ('temperatura_corporal', models.CharField(max_length=45)),
                ('pulso', models.CharField(max_length=45)),
                ('frecuencia_respiratoria', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'signos_vitales',
                'managed': True,
            },
        ),
    ]
