# Generated by Django 5.1 on 2025-12-01 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitaciones', '0002_initial'),
        ('internacion', '0001_initial'),
        ('pacientes', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='idmedico',
            field=models.ForeignKey(db_column='idMedico', on_delete=django.db.models.deletion.PROTECT, to='personal.medico'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='idmedico_derivado',
            field=models.ForeignKey(blank=True, db_column='idMedico_derivado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnostico_como_derivado', to='personal.medico'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='idpaciente',
            field=models.ForeignKey(db_column='idPaciente', on_delete=django.db.models.deletion.PROTECT, to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='cama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitaciones.cama'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='idpaciente',
            field=models.ForeignKey(db_column='idPaciente', on_delete=django.db.models.deletion.PROTECT, to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='idinternacion',
            field=models.ForeignKey(blank=True, db_column='idInternacion', null=True, on_delete=django.db.models.deletion.CASCADE, to='internacion.internacion'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='cama_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_destino', to='habitaciones.cama'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='cama_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_origen', to='habitaciones.cama'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='idenfermero',
            field=models.ForeignKey(db_column='idEnfermero', on_delete=django.db.models.deletion.PROTECT, to='personal.enfermero'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='idinternacion',
            field=models.ForeignKey(db_column='idInternacion', on_delete=django.db.models.deletion.CASCADE, to='internacion.internacion'),
        ),
        migrations.AddField(
            model_name='medicacion',
            name='seguimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicaciones', to='internacion.seguimiento'),
        ),
        migrations.AddField(
            model_name='signosvitales',
            name='seguimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signos_vitales', to='internacion.seguimiento'),
        ),
    ]
