# Generated by Django 5.1 on 2025-04-14 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internacion', '0001_initial'),
        ('personal', '0003_alter_persona_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='idmedico_derivado',
            field=models.ForeignKey(blank=True, db_column='diagnostico_como_derivado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnostico_como_derivado', to='personal.medico'),
        ),
    ]
