# Generated by Django 5.1 on 2025-04-15 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0009_alter_sector_tipo'),
        ('internacion', '0003_alter_diagnostico_idmedico_derivado'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='cama_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_destino', to='habitaciones.cama'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='cama_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_origen', to='habitaciones.cama'),
        ),
    ]
