# Generated by Django 5.1 on 2025-05-19 19:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internacion', '0004_seguimiento_cama_destino_seguimiento_cama_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='fecha',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
