# Generated by Django 5.1 on 2025-03-08 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='username',
        ),
    ]
